# Generated by Django 4.2.1 on 2023-11-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_category_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
