# Generated by Django 4.2.1 on 2023-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_tagpost_alter_women_cat_women_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
